apiVersion: v1
entries:
  netobserv-operator:
  - apiVersion: v2
    appVersion: 1.8.1-community
    created: "2025-03-11T12:32:14.802549475+01:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 97703c8ed100b957172dae10e8227d835613b57931b170fa884a9897ad187819
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.1-community.tgz
    version: 1.8.1-community
  - apiVersion: v2
    appVersion: 1.8.0-community
    created: "2025-03-11T12:32:14.799962482+01:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 95a50e7776c6fa5d5ff5d2986a5d83700e29e73dcdd04d7fc4c0d5c70a604192
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.0-community.tgz
    version: 1.8.0-community
generated: "2025-03-11T12:32:14.79647498+01:00"
