apiVersion: v1
entries:
  NetObserv operator:
  - apiVersion: v2
    appVersion: 1.8.0-community
    created: "2025-03-10T17:07:25.931253726+01:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 199d20e15e453ca6161f98431353fca535af7a8f3b55122a67885d2fee9ad611
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: NetObserv operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/NetObserv%20operator-1.8.0-community.tgz
    version: 1.8.0-community
generated: "2025-03-10T17:07:25.927684387+01:00"
